spring:
  application:
    name: auth-service
  neo4j:
    uri: ${NEO4J_URI:bolt://127.0.0.1:7687}
    authentication:
      password: ${NEO4J_PASSWORD:password}
      username: ${NEO4j_USERNAME:neo4j}

server:
  port: 8050

aws:
  region: us-east-1
  endpoint: ${AWS_ENDPOINT:#{null}}
  kms:
    keyId: ${JWT_KEY_ID:00000000-0000-0000-0000-000000000002}
